#!/usr/bin/env ansible-playbook
---
- name: Deploy postgres on db
  hosts: db
  vars_files:
    - secrets.yaml

  roles:
    - role: database
      tags: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"
