VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config |
    config.vagrant.plugins = ["vagrant-hostmanager"]
    # Use the same key for each machine
    config.ssh.insert_key = false
    # manage /etc/hosts
    config.hostmanager.enabled = true
    config.hostmanager.include_offline = true
    config.hostmanager.manage_guest = true
    config.hostmanager.manage_host = true

    config.vm.define "vagrant1" do |vagrant1|
        vagrant1.vm.box = "ubuntu/focal64"
        vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
        vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
        vagrant1.vm.network "forwarded_port", guest: 8000, host: 8000 
    end
end